### PR TITLE
modified message

### PR DESCRIPTION
**Pull request by asukaltair**
### description
 - add aiueo

### CODE REVIEW

**Comment by rartuyo** [comment]
Please change aiueo to ka ki ku ke ko

**Comment by asukaltair** [comment]
> Please change aiueo to ka ki ku ke ko

i changed from aiueo to kakikukeko

**Review by rartuyo — COMMENTED** [review]
Change Hoge to Lorem

**Comment by asukaltair** [comment]
i changed from hoge to Lorem

**Review by rartuyo — APPROVED** [review]

**Pull request merged**
